name: CreatorGames
version: ${project.version}
main: jackgnuk.creatorgames.CreatorGames
api-version: 1.16
authors: [ JackGNUK, 007spy9 ]
softdepend:
  - PartyGames
  - TitleManager
commands:
  top:
    aliases: test
    description: display leaderboard from creatorgames
  addteammate:
    description: Add a teammate to a specified team by ID. Team should be in config.yml
  removeteammate:
    description: Remove a teammate from a specified team by ID. Team should be in config.yml